### ISSUE TITLE
PyStemmer vs pyporter2

### ISSUE THREAD

**Issue by turian** [mdirolf/pyporter2#1]
I am getting some minorly different results between PyStemmer's Python wrapper around the Snowball stemmer and the pyporter2 pure-python implementation.

word = u'eug\xe8neysa\xffe'
PyStemmer = u'eug\xe8neysa\xffe'
pyporter2 = u'eug\xe8neysa\xff

This happens with a variety of terms when the second-to-last term is a funny character:
u'czy\u017ce'
u'my\u014de'
u'bornholmerstra\xdfe'
etc.'

p.s. Thank you for pyporter2, it's very useful for GAE apps. NLTK's stemmers are all inconsistent with respect to the Snowball implementation, even nltk.stem.snowball. Maybe you should put that in the documentation. I found out the hard way.

**Comment by mdirolf** [comment]
Thanks for the heads up. I just pushed a change that should return all non-ascii words as-is. The algorithm's definition - http://snowball.tartarus.org/algorithms/english/stemmer.html - doesn't really state what to do in that case, but it seems like that's what PyStemmer is doing.
