### ISSUE TITLE
License

### ISSUE THREAD

**Issue by langston-barrett** [mdirolf/pyporter2#2]
I can't seem to find the license for this code. From http://choosealicense.com/no-license [1]:

> You’ll have to check with your own legal counsel regarding your particular project, but generally speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

Did you intend for this code to be open source? If so, can you upload a license, or point me to it?

Thanks!

[1]: See also: the Berne Convention, the international law: http://zvon.org/law/r/bern.html#intro

**Comment by mdirolf** [comment]
It's MIT: https://github.com/mdirolf/pyporter2/blob/master/Stemmer.py#L3-L22

**Comment by langston-barrett** [comment]
@mdirolf Thanks for the pointer! Generally, people include a LICENSE file in the root of the repo, which might help other people looking for it!
